### ISSUE TITLE
Can you share documentation and wiring diagram?

### ISSUE THREAD

**Issue by civanahmetyasin** [jerajp/RCtransmitter#1]
Can you share documentation and wiring diagram? Can you share the pin connections and circuit diagrams? Thank you.

Ahmet Yasin CİVAN
Turkey!

**Comment by jerajp** [comment]
Thank you for your interest. I will put together some schematics of HW over the weekend (or so i hope). The project multiplied quite a bit from my simple first version.

In short HW consists of :
-control board Blue pill with STM32F103C8T6
-NRF24L01 module for wifi connection (waiting for ones with shield over PCB, the regular ones are not the most reliable)
-2 potenciometers,
-2 joystics from Flysky FS-TH9X (toy button like joystics are garbage for drone control)  
-6 toggle switches 
-nokia lcd 5110
-MCP23017  I/O expander (ran out of pins)
-BMS 2 cell li-ion 18650
-buck converter (step down voltage from DC supply input for BMS)
-4 trim pushbuttons per joystick (++,-- offset for each axis)
-8 pushbuttons for LCD menu control
-buzzer for low battery status
-4 LED for status+
-All is accomodated in plastic casing of my design and can be 3D printed

General idea was to have custom communication with drone. I recently added commands to tune parameters like pid constants and save them in Flash of uP of the Drone. 


![RC remote](https://user-images.githubusercontent.com/55595820/101906330-13ac9c80-3bb9-11eb-95d2-7347852d8ddb.jpg)

**Comment by civanahmetyasin** [comment]
Thanks for coming back.This is awesome, I like this picture, thank you. I studied the codes and liked it very much. I have to use STM32F103C8T6 and 5110 with NRF for greenhouse automation project. You repo very useful. You should this picture add README.md

Thank you. Please, add me on linkedin. 
Ahmet Yasin CİVAN.
Turkey!
